DELETE FROM TRIP;
DELETE FROM ROUTE;
DELETE FROM CAR;
DELETE FROM MEMBER;
DELETE FROM USER;


-- INSERT VALUES IN USER
INSERT INTO USER VALUES (1, 'Christophe', 'QUENETTE', 'christophe.quenette@etu.umontpellier.fr');
-- INSERT INTO USER VALUES (2, '')

-- INSERT VALUES IN MEMBER
INSERT INTO MEMBER VALUES (1, 75, 'Avenue',  'Augustin Fliche', 'Montpellier', '+33750867489', 5.6); -- Test de note trop élévée

-- INSERT VALUES IN CAR
INSERT INTO CAR VALUES (1, 'AA-123-AA', 1, 'Kangoo', 'Renault', 2009, 5);

-- INSERT VALUES IN ROUTE
INSERT INTO ROUTE VALUES (1, 'Lille', 'Montpellier');

-- INSERT VALUES IN TRIP
INSERT INTO TRIP VALUES (1, 1, "2017-12-13");
