use cquenette

DROP TABLE TRAVEL CASCADE;
DROP TABLE TRIP CASCADE;
DROP TABLE CAR CASCADE;
DROP TABLE MEMBER CASCADE;
DROP TABLE ADMIN CASCADE;
DROP TABLE USER CASCADE;

CREATE TABLE IF NOT EXISTS USER (
    userID INT NOT NULL AUTO_INCREMENT,
    firstName VARCHAR(255),
    lastName VARCHAR(255),
    admin TINYINT(1),
    email VARCHAR(320),
    password VARCHAR(255),
    adressNumber NUMERIC(6),
    adressStreetType VARCHAR(20),
    adressStreetName VARCHAR(50),
    adressCity VARCHAR(50),
    phone VARCHAR(15),
    CONSTRAINT PK_USER PRIMARY KEY USER(userID),
    CONSTRAINT UC_USER UNIQUE (userID)
)ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS ADMIN (
    adminID INT NOT NULL,
    CONSTRAINT FK_ADMIN_USER FOREIGN KEY (adminID) REFERENCES USER(userID),
    CONSTRAINT UC_ADMIN UNIQUE (adminID)
)ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS MEMBER (
    memberID INT NOT NULL,
    birthDate date NOT NULL,
    review NUMERIC(2,1),
    driver INT,
    CONSTRAINT FK_MEMBER_USER FOREIGN KEY (memberID) REFERENCES USER(userID),
    CONSTRAINT FK_CAR_DRIVER FOREIGN KEY (driver) REFERENCES MEMBER(memberID),
    CONSTRAINT CHK_MEMBER_REVIEW CHECK (review BETWEEN 0.0 AND 5.0),
    CONSTRAINT UC_MEMBER UNIQUE (memberID)
)ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS CAR (
    carID INT AUTO_INCREMENT NOT NULL,
    numberPlate VARCHAR(15) NOT NULL,
    owner INT NOT NULL,
    model VARCHAR(20),
    brand VARCHAR(20),
    year NUMERIC(4),
    capacity NUMERIC(2) NOT NULL,
    CONSTRAINT PK_CAR PRIMARY KEY CAR(carID),
    CONSTRAINT FK_CAR_MEMBER FOREIGN KEY (owner) REFERENCES MEMBER(memberID),
    CONSTRAINT NN_CAR_OWNER CHECK (owner IS NOT NULL),
    UNIQUE (numberPlate, carID)
)ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS TRIP (
    tripID INT AUTO_INCREMENT NOT NULL,
    departureCity VARCHAR(40) NOT NULL,
    arrivalCity VARCHAR(40) NOT NULL,
    price INT NOT NULL,
    CONSTRAINT PK_TRIP PRIMARY KEY TRIP(tripID),
    CONSTRAINT UC_MEMBER UNIQUE (tripID)
)ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS TRAVEL (
    tripID INT NOT NULL,
    memberID INT NOT NULL,
    travelDate date NOT NULL,
    CONSTRAINT PK_TRAVEL PRIMARY KEY TRAVEL(tripID, memberID),
    CONSTRAINT FK_TRAVEL_TRIP FOREIGN KEY (tripID) REFERENCES TRIP(tripID),
    CONSTRAINT FK_TRAVEL_MEMBER FOREIGN KEY (memberID) REFERENCES MEMBER(memberID)
)ENGINE=INNODB;
