use cquenette

DROP TABLE TRIP CASCADE;
DROP TABLE ROUTE CASCADE;
DROP TABLE CAR CASCADE;
DROP TABLE MEMBER CASCADE;
DROP TABLE USER CASCADE;

CREATE TABLE IF NOT EXISTS USER (
    userID INT NOT NULL AUTO_INCREMENT,
    firstName VARCHAR(255),
    lastName VARCHAR(255),
    email VARCHAR(320),
    password VARCHAR(255),
    CONSTRAINT PK_USER PRIMARY KEY USER(userID)
)ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS MEMBER (
    memberID INT NOT NULL,
    adressNumber NUMERIC(6),
    adressStreetType VARCHAR(20),
    adressStreetName VARCHAR(50),
    adressCity VARCHAR(50),
    phone VARCHAR(15),
    review NUMERIC(2,1),
    passenger INT,
    CONSTRAINT FK_MEMBER_USER FOREIGN KEY (memberID) REFERENCES USER(userID),
    CONSTRAINT FK_CAR_PASSENGER FOREIGN KEY (passenger) REFERENCES MEMBER(memberID),
    CONSTRAINT CHK_MEMBER_REVIEW CHECK (review BETWEEN 0.0 AND 5.0)
)ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS CAR (
    carID INT AUTO_INCREMENT,
    numberPlate VARCHAR(15),
    owner INT,
    model VARCHAR(20),
    brand VARCHAR(20),
    year NUMERIC(4),
    capacity NUMERIC(2),
    departureCity VARCHAR(40),
    arrivalCity VARCHAR(40),
    date DATE NOT NULL,
    CONSTRAINT PK_CAR PRIMARY KEY CAR(carID),
    CONSTRAINT FK_CAR_MEMBER FOREIGN KEY (owner) REFERENCES MEMBER(memberID),
    CONSTRAINT NN_CAR_OWNER CHECK (owner IS NOT NULL),
    UNIQUE (numberPlate)
)ENGINE=INNODB;
